token:

panels:
  download:
    title: Polar Downloads
    description: This is an area where you can download the polar products
    footer: Polar Downloads
    color: 11393254
    channel: 1000058297715523615

products:
  polar-vaults:
    name: Vaults
    table: vaults
    url: https://auth.polar.com/v1/downloads/vault
    libraries: [ ]

database:
  query: SELECT * FROM %s WHERE discord = ?
  username: root
  password: pass
  host: localhost
  port: 3306
  dbname: polar
  use-ssl: false
  ssl:
    username: user
    password: pass
    host: localhost
    port: 22